# Generated by Django 3.1.2 on 2022-07-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120)),
                ('csv_file', models.FileField(upload_to='csvs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sembrada', models.FloatField(help_text='Ha')),
                ('area_cosechada', models.FloatField(help_text='Ha')),
                ('produccion', models.FloatField(help_text='T')),
                ('rendimiento', models.FloatField(help_text='T/Ha')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio')),
            ],
        ),
    ]
