# Generated by Django 3.1.2 on 2022-07-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_csv_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='period',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='year',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
