# Generated by Django 3.1.2 on 2022-01-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('irradiance', models.FloatField(help_text='MJ/m^2/day')),
                ('temperature', models.FloatField(help_text='°C')),
                ('relative_humidity', models.FloatField(help_text='%')),
                ('precipitation', models.FloatField(help_text='mm/day')),
                ('territorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorios.territorio')),
            ],
        ),
    ]
