# Generated by Django 3.1.2 on 2022-01-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorios', '0003_auto_20220128_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorio',
            name='latitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territorio',
            name='longitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
